### ISSUE TITLE
Menus not working

### ISSUE THREAD

**Issue by mraf** [givanz/Vvveb#136]
Hi,

I've tried to update menu item links or titles in my vvveb instalation and demo, but it seems like edit button does not work. I've also tried different browsers too but no luck

<img width="1502" alt="image" src="https://github.com/givanz/Vvveb/assets/10253590/dfe22262-d78b-4b98-b27b-a911be7782cc">

When adding a new menu item, it appears in the list but disappears after saving. 

<img width="1497" alt="image" src="https://github.com/givanz/Vvveb/assets/10253590/fc18159d-6507-4bee-bdd1-42c6cb229ef5">

Deleting an item from the list works, but only after pressing the save button. Can we make it more intuitive so admin user will know that item has been deleted as for now may think nothing changed?

**Comment by givanz** [comment]
Hi

Thanks for the bug reports, I fixed menu item edit not opening https://github.com/givanz/vvveb-admin-template/commit/ba3d82fac66176cb403f13b50560d7fa672e5ccb

> When adding a new menu item, it appears in the list but disappears after saving.

I need to change the interface to make it more clear that the save button is saving only menu name and slug and that menu items have each their own save button in the expanded form that is shown after clicking edit.

> Deleting an item from the list works, but only after pressing the save button

Delete menu item will remove the item and show a notice at the bottom of the screen.

I think that delete was not working properly because of the javascript error that also prevented edit from working.

**Comment by mraf** [comment]
Thanks for quick update on this!
