### ISSUE TITLE
Image Upload Logo Not Working

### ISSUE THREAD

**Issue by silicahd** [givanz/Vvveb#63]
1. Cant upload images from settings site page 
2. If you change the logo in the nav bar it will not save. 
3. Cant change SVG color 
4. Images will not load after you upload them. 
![image](https://github.com/givanz/Vvveb/assets/7761519/4586a6e0-47da-4ad8-b3db-631cc1fd0c8d)

It looks like the toast is still over it after you upload an image. 

![image](https://github.com/givanz/Vvveb/assets/7761519/d67dc149-7677-4d4c-ab3c-8121a76afd04)

**Comment by givanz** [comment]
Thanks for the bug report, upload and toast/modal z-index issues are fixed in the last update https://github.com/givanz/Vvveb/commit/1b27afb60e7ea64554ec5915c6834e789946922c https://github.com/givanz/vvveb-admin-template/commit/fbd7511d46245ced56a23a4b4b2b12fa636a8461


You can redownlad latest.zip and update `public/admin` and `admin/` folders.

Can you please provide more details about the SVG color issue?
