### ISSUE TITLE
Сustom favicon favicon in admin panel not overlap theme favicon

### ISSUE THREAD

**Issue by lilianzzz** [givanz/Vvveb#81]
There is an assumption that the template favicon (is it even needed at the template level?) has higher priority than the favicon in the admin settings

It’s problematic to check completely - the favicon is apparently cached at my server level and takes N-hours to change

**Comment by givanz** [comment]
The theme usually has a default favicon that is overwritten by site settings.

Any theme is a standalone working static html template/site  and for this they have proper defaults for everything.

Html files can even be opened directly from theme folder in the browser and display properly.

This issue was caused because blink theme was missing ` data-v-global-site-favicon` attribute on favicon element 

```html
<link rel="shortcut icon" type="image/x-icon" href="img/favicon.png" data-v-global-site-favicon>
```

You can redownload the theme or add the attribute manually in index.html and clear cache.

**Comment by lilianzzz** [comment]
Thank you very much for the explanations. works! =)
